services:
  Jolicht\DogadoSerializerBundle\Normalizer\AggregateRootIdNormalizer:
    tags: ['serializer.normalizer']

  Jolicht\DogadoSerializerBundle\Normalizer\SerializablePayloadNormalizer:
    tags: ['serializer.normalizer']